---
name: cmpsc-100-fall-2018-inclass
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        inclass/ExploreDataTypes.java:
            --count 33
            --single 2 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 4 --exact
            --fragment "new Date(" --count 1 --exact
            --fragment "TODO" --count 0 --exact
src/main:
    java:
        inclass/ComputeGasMileage.java:
            --count 35
            --single 4 --language Java
            --multi 2 --language Java
            --fragment "print(" --count 2 --exact
            --fragment "println(" --count 1 --exact
            --fragment "TODO" --count 0 --exact
src/main:
    java:
        inclass/DisplayLogisticMap.java:
            --count 95
src/main:
    java:
        inclass/PerformStringMutation.java:
            --count 40
            --fragment "println(" --count 7 --exact
            --fragment "TODO" --count 0 --exact
src/main:
    java:
        inclass/CompareInputValues.java:
            --count 37
            --single 4 --language Java
            --multi 2 --language Java
            --fragment "print(" --count 2 --exact
            --fragment "println(" --count 2 --exact
            --fragment "TODO" --count 0 --exact
src/main:
    java:
        inclass/ComputeAverage.java:
            --count 50
            --single 8 --language Java
            --multi 2 --language Java --exact
            --fragment "println(" --count 4 --exact
            --fragment "TODO" --count 0 --exact
src/main:
    java:
        inclass/ComputeMultiples.java:
            --count 63
            --single 22 --language Java --exact
            --multi 3 --language Java --exact
            --fragment "println(" --count 3 --exact
            --fragment "TODO" --count 0 --exact
writing/coveros.md:
    mdl
    proselint
    --paragraphs 1 --exact
    --words 100
