---
name: cmpsc-100-fall-2018-inclass
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        inclass/ExploreDataTypes.java:
            --count 33
            --single 2 --language Java
            --multi 2 --language Java
            --fragment "println(" --count 4 --exact
            --fragment "new Date(" --count 1 --exact
src/main:
    java:
        inclass/ComputeGasMileage.java:
            --count 35
            --single 4 --language Java
            --multi 2 --language Java
            --fragment "print(" --count 2 --exact
            --fragment "println(" --count 1 --exact
